require('./arc-test');
require('./doublearc-test');
require('./game-test');
require('./grid-test');
require('./line-test');
require('./pattern-generator-test');
require('./quadarc-test');
require('./renderer-test');
require('./spoke-test');
